#!/usr/bin/env node
"use strict";

/**
 * 装/卸「企微守护看门狗」的 Windows 计划任务（参考既有 pi-watchdog 的做法）。
 *
 * 用法：
 *   node scripts/装企微看门狗.cjs            # 安装（幂等，可反复执行）
 *   node scripts/装企微看门狗.cjs --remove   # 卸载（删计划任务 + 启动器）
 *
 * 安装后：
 *   - 在 %USERPROFILE%\.config\wecom-watchdog\ 生成隐藏窗口启动器 watchdog.ps1；
 *   - 注册计划任务 wecom-daemon-watchdog，每 5 分钟跑一次 scripts/企微看门狗.js；
 *   - 看门狗独立于 pi 窗口存活（pi 窗关了它照样巡）。
 *
 * 为什么是 5 分钟：群/单聊静默阈值是小时级，5 分钟足够"尽早发现"；
 * 又不至于太频繁（每次只读尾部文件 + tasklist，几乎不耗资源）。
 */

const fs = require("fs");
const path = require("path");
const os = require("os");
const { spawnSync } = require("child_process");

const ROOT = path.join(__dirname, "..");
const WATCHDOG_JS = path.join(__dirname, "企微看门狗.js");
const NODE_EXE = process.execPath;
const CONF_DIR = path.join(os.homedir(), ".config", "wecom-watchdog");
const WRAPPER = path.join(CONF_DIR, "watchdog.ps1");
const TASK_NAME = "wecom-daemon-watchdog";

function psQuote(s) {
  return "'" + String(s).replace(/'/g, "''") + "'";
}

function runPowerShellFile(file) {
  return spawnSync("powershell.exe", ["-NoProfile", "-ExecutionPolicy", "Bypass", "-File", file], {
    encoding: "utf8",
    windowsHide: true,
    timeout: 120000
  });
}

function runPowerShellCommand(cmd) {
  return spawnSync("powershell.exe", ["-NoProfile", "-Command", cmd], {
    encoding: "utf8",
    windowsHide: true,
    timeout: 120000
  });
}

function writeUtf8Bom(file, text) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, "\uFEFF" + text, "utf8"); // PS 5.1 无 BOM 会按 ANSI 读 → 中文路径乱码
}

function install() {
  if (!fs.existsSync(WATCHDOG_JS)) throw new Error(`找不到看门狗脚本：${WATCHDOG_JS}`);

  // ① 隐藏窗口启动器（SQL 只负责把 node 跑起来；逻辑全在企微看门狗.js）
  const wrapper = [
    "# Generated by 27.企业微信机器人/scripts/装企微看门狗.cjs — thin launcher, do not edit by hand.",
    "$ErrorActionPreference = 'Continue'",
    "[Console]::OutputEncoding = [System.Text.Encoding]::UTF8",
    "$OutputEncoding = [System.Text.Encoding]::UTF8",
    `$node = ${psQuote(NODE_EXE)}`,
    `$script = ${psQuote(WATCHDOG_JS)}`,
    "$outLog = Join-Path $PSScriptRoot 'watchdog.out.log'",
    "try {",
    "  if ((Test-Path $outLog) -and ((Get-Item $outLog).Length -gt 1MB)) { Move-Item -Force $outLog ($outLog + '.1') }",
    "} catch {}",
    "& $node $script *>&1 | Out-File -FilePath $outLog -Append -Encoding utf8",
    "exit $LASTEXITCODE",
    ""
  ].join("\r\n");
  writeUtf8Bom(WRAPPER, wrapper);

  // ② 注册计划任务（一次性触发 + 每 5 分钟重复 = 无限循环）
  const register = [
    "$ErrorActionPreference = 'Stop'",
    `$taskName = ${psQuote(TASK_NAME)}`,
    `$ps = ${psQuote(WRAPPER)}`,
    "$action = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument ('-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File \"' + $ps + '\"')",
    "$trigger = New-ScheduledTaskTrigger -Once -At (Get-Date) -RepetitionInterval (New-TimeSpan -Minutes 5)",
    "$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -MultipleInstances IgnoreNew -ExecutionTimeLimit (New-TimeSpan -Minutes 10)",
    "Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Settings $settings -Description '企微长连接守护看门狗（27.企业微信机器人）每5分钟巡检：进程/认证/群与单聊消息新鲜度' -Force | Out-Null",
    "Start-ScheduledTask -TaskName $taskName",
    "Start-Sleep -Seconds 2",
    "Get-ScheduledTask -TaskName $taskName | Select-Object TaskName, State | Format-List",
    "Get-ScheduledTaskInfo -TaskName $taskName | Select-Object LastRunTime, LastTaskResult, NextRunTime | Format-List",
    ""
  ].join("\r\n");
  const tmp = path.join(CONF_DIR, "register.ps1");
  writeUtf8Bom(tmp, register);
  try {
    const r = runPowerShellFile(tmp);
    if (r.status !== 0) throw new Error(`注册计划任务失败：${(r.stderr || r.stdout || "").trim()}`);
    console.log((r.stdout || "").trim());
  } finally {
    try { fs.unlinkSync(tmp); } catch {}
  }
  console.log(`已安装：任务 ${TASK_NAME}（每 5 分钟）→ ${WATCHDOG_JS}`);
  console.log(`启动器：${WRAPPER}`);
  console.log("验证：schtasks /query /tn " + TASK_NAME + " /v /fo LIST  或者  Get-Content \"" + path.join(ROOT, ".state", "看门狗.log") + "\" -Tail 10");
}

function remove() {
  const r = runPowerShellCommand(`Unregister-ScheduledTask -TaskName ${psQuote(TASK_NAME)} -Confirm:$false -ErrorAction SilentlyContinue`);
  console.log((r.stdout || r.stderr || "").trim() || "已卸载（任务可能本来就不存在）");
  try { fs.unlinkSync(WRAPPER); console.log(`已删除启动器：${WRAPPER}`); } catch {}
}

try {
  if (process.argv.includes("--remove")) remove();
  else install();
} catch (err) {
  console.error((err && err.message) || err);
  process.exitCode = 1;
}
