// 该文件只负责抖音下载流程的超时与轮询参数。
const DOUYIN_DOWNLOAD_TIMEOUT_MS = 60000;
const DOUYIN_POLL_INTERVAL_MS = 1000;
const DOUYIN_STORE_ID_READ_TIMEOUT_MS = 10000;
const DOUYIN_LOGIN_RECOVERY_TIMEOUT_MS = 10 * 60 * 1000;
const DOUYIN_STORE_SWITCH_TIMEOUT_MS = 10 * 60 * 1000;

module.exports = {
  DOUYIN_DOWNLOAD_TIMEOUT_MS,
  DOUYIN_POLL_INTERVAL_MS,
  DOUYIN_STORE_ID_READ_TIMEOUT_MS,
  DOUYIN_LOGIN_RECOVERY_TIMEOUT_MS,
  DOUYIN_STORE_SWITCH_TIMEOUT_MS
};
