// 该文件只负责抖音下载流程的超时与轮询参数。
const DOUYIN_DOWNLOAD_TIMEOUT_MS = 60000;
const DOUYIN_POLL_INTERVAL_MS = 1000;
const DOUYIN_STORE_ID_READ_TIMEOUT_MS = 10000;
const DOUYIN_LOGIN_RECOVERY_TIMEOUT_MS = 10 * 60 * 1000;
const DOUYIN_STORE_SWITCH_TIMEOUT_MS = 10 * 60 * 1000;
const DOUYIN_DATE_CONTROL_IDLE_TIMEOUT_MS = 30000;
// 2026-09-30 假过期治理：抖音登录页壳/登录提示是页面级瞬时状态（SPA 换路由、旧文案残留），
// 判定“登录已过期”之前必须先给宽限期并就同一信号连续确认，否则会白弹一次人工登录窗口。
const DOUYIN_LOGIN_FALSE_EXPIRY_GRACE_MS = 45 * 1000;
const DOUYIN_LOGIN_CONFIRM_INTERVAL_MS = 2500;
const DOUYIN_LOGIN_CONFIRM_ATTEMPTS = 2;

module.exports = {
  DOUYIN_DOWNLOAD_TIMEOUT_MS,
  DOUYIN_POLL_INTERVAL_MS,
  DOUYIN_STORE_ID_READ_TIMEOUT_MS,
  DOUYIN_LOGIN_RECOVERY_TIMEOUT_MS,
  DOUYIN_STORE_SWITCH_TIMEOUT_MS,
  DOUYIN_DATE_CONTROL_IDLE_TIMEOUT_MS,
  DOUYIN_LOGIN_FALSE_EXPIRY_GRACE_MS,
  DOUYIN_LOGIN_CONFIRM_INTERVAL_MS,
  DOUYIN_LOGIN_CONFIRM_ATTEMPTS
};
