# 该文件用于组装扫描当前可见订单行的浏览器脚本。
from __future__ import annotations

from .ag_collector import VISIBLE_ORDER_ROWS_AG_COLLECTOR
from .candidate_scoring import VISIBLE_ORDER_ROWS_CANDIDATE_SCORING
from .dom_helpers import VISIBLE_ORDER_ROWS_DOM_HELPERS
from .entry_flow import VISIBLE_ORDER_ROWS_ENTRY_FLOW
from .other_collectors import VISIBLE_ORDER_ROWS_OTHER_COLLECTORS
from .prologue import VISIBLE_ORDER_ROWS_PROLOGUE
from .row_alignment import VISIBLE_ORDER_ROWS_ALIGNMENT

_VISIBLE_ORDER_ROWS_SCRIPT_PARTS = (
    VISIBLE_ORDER_ROWS_PROLOGUE,
    VISIBLE_ORDER_ROWS_DOM_HELPERS,
    VISIBLE_ORDER_ROWS_ALIGNMENT,
    VISIBLE_ORDER_ROWS_AG_COLLECTOR,
    VISIBLE_ORDER_ROWS_OTHER_COLLECTORS,
    VISIBLE_ORDER_ROWS_CANDIDATE_SCORING,
    VISIBLE_ORDER_ROWS_ENTRY_FLOW,
)

SCAN_VISIBLE_ORDER_ROWS_SCRIPT = "\n" + "\n\n".join(part.strip("\n") for part in _VISIBLE_ORDER_ROWS_SCRIPT_PARTS) + "\n"

__all__ = ["SCAN_VISIBLE_ORDER_ROWS_SCRIPT"]
